CREATE TABLE `nilai` (
  `nis` int(11) NOT NULL,
  `id_kelas` int(11) NOT NULL,
  `kd_mp` int(11) NOT NULL,
  `nilai_tp1` int(4) DEFAULT NULL,
  `nilai_tp2` int(4) DEFAULT NULL,
  `nilai_tp3` int(4) DEFAULT NULL,
  `nilai_tp4` int(4) DEFAULT NULL,
  `nilai_tp5` int(4) DEFAULT NULL,
  `nilai_tp6` int(4) DEFAULT NULL,
  `nilai_tp7` int(4) DEFAULT NULL,
  `rata_tp` int(4) DEFAULT NULL,
  `nilai_uh1` int(4) DEFAULT NULL,
  `nilai_uh2` int(4) DEFAULT NULL,
  `nilai_uh3` int(4) DEFAULT NULL,
  `nilai_uh4` int(4) DEFAULT NULL,
  `nilai_uh5` int(4) DEFAULT NULL,
  `nilai_uh6` int(4) DEFAULT NULL,
  `nilai_uh7` int(4) DEFAULT NULL,
  `rata_uh` int(4) DEFAULT NULL,
  `nilai_pts` int(4) DEFAULT NULL,
  `nilai_uas` int(4) DEFAULT NULL,
  `nilai_akhir` int(4) DEFAULT NULL,
  `nilai_huruf` enum('A', 'B', 'C', 'D', 'E') DEFAULT NULL,
  `deskripsi` mediumtext DEFAULT NULL,
  PRIMARY KEY (`nis`, `id_kelas`, `kd_mp`),
  FOREIGN KEY (`nis`) REFERENCES `siswa`(`nis`),
  FOREIGN KEY (`id_kelas`) REFERENCES `kelas`(`id_kelas`),
  FOREIGN KEY (`kd_mp`) REFERENCES `mata_pelajaran`(`kd_mp`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
